// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/templates/Button/index.vue')['default']
    Draggable: typeof import('./components/Draggable/index.vue')['default']
    DropContent: typeof import('./components/DropContent/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Loading: typeof import('./components/Loading/index.vue')['default']
    Overlay: typeof import('./components/Overlay/index.vue')['default']
    Paragraph: typeof import('./components/templates/Paragraph/index.vue')['default']
    Sidebar: typeof import('./components/Sidebar/index.vue')['default']
  }
}

export { }
